# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
# Updates CODEQL yml 

name: Swift

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1.0'

    - name: Install Tailor
      run: brew install tailor

    - name: Run Tailor Analysis
      run: tailor lint .

    - name: Build
      run: swift build

    - name: Run tests
      run: swift test

    - name: Save Tailor Report
      run: tailor lint . > tailor-report.txt

    - name: Upload Tailor Report
      uses: actions/upload-artifact@v3
      with:
        name: tailor-report
        path: tailor-report.txt

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: .build/debug/codecov.json 

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: .build 
